name: Build Chroma

on: 
  push:
    branches: 
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2

      - name: Mingw
        run: |
          apt-get install mingw-w64

      - name: Setup
        run: |
          cmake ./

      - name: Setup
        run: |
          make purpuri
      
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: |
            bin/      