name: Build Chroma

on: 
  push:
    branches: 
      - master

jobs:
    build:
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2

      - name: Setup
        run: |
          cmake ./