name: Build Windows Package (With Debugger)

on: 
  push:
    branches: 
      - master

jobs:
    build:
      runs-on: windows-latest
      
      defaults:
       run:
        shell: msys2 {0}

      steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-gcc
            git
            cmake
            
      - uses: actions/checkout@v2
      
      - name: Cmake Initialization
        run: |
          cmake -D debugger= ./ 
          
      - name: Build
        run: |
          make purpuri
      
      - uses: actions/upload-artifact@v2
        with:
          name: binary
          path: |
            bin/
